language: go
go:
  - 1.11.x
go_import_path: arp242.net/trackwall
notifications:
  email: false
cache:
  directories:
    - $HOME/.cache/go-build
install:
  - ./bin/setup-travis
script:
  - cd $HOME/gopath/src/arp242.net/trackwall
  - "[ -f go.sum ] && export GO111MODULE=on"
  - ./bin/coverage -race ./...
  - ./bin/lint ./...
