language: go
go:
  - 1.8.x
  - 1.9.x
go_import_path: arp242.net/trackwall
notifications:
  email: false
cache:
  directories:
    - $HOME/gopath/pkg
install: []
script:
  - cd $HOME/gopath/src/arp242.net/trackwall
  - ./bin/test
  - ./bin/coverage
  - ./bin/lint
